name: PHP CI with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup PHP with Xdebug for code coverage
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
          extensions: mbstring, xml, curl, zip, mysql

      # Install Composer dependencies
      - name: Install dependencies with composer
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      # Create .env file and generate APP_KEY
      - name: Create .env file and generate key
        run: |
          cp .env.example .env
          php artisan key:generate

      # Run PHPUnit tests and generate code coverage report
      - name: Run tests with PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      # Run SonarQube scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: sqp_ee292862bac36fddc46eadbb2bd7d920a33918e0   # Use GitHub Secrets to securely store SonarQube token
          SONAR_HOST_URL: http://44.201.244.61:9000
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=php-app
            -Dsonar.sources=.
            -Dsonar.php.coverage.reportPaths=coverage.xml
